#!/bin/bash
FROM=1
TO=4294967296
while getopts "hm:f:t:s" OPT; do
  case $OPT in
    "h") usage;; # show help
    "m") TITLE=$OPTARG;;
    "f") FROM=$OPTARG;;
    "t") TO=$OPTARG;;
    "?") exit -1;;
  esac
done

if [ -z "$TITLE" ]; then 
  echo -n "Search: "
  read -r query
else
  query=$TITLE
fi
# if the search query is empty, quit
if [ -z "$query" ]; then exit; fi 

echo "Searching..."
# sanitise the query
query=$(sed \
	-e 's|+|%2B|g'\
	-e 's|#|%23|g'\
	-e 's|&|%26|g'\
	-e 's| |%20|g'\
	<<< "$query")

# sort -u to remove duplicates
response="$(curl -s "https://w12.mangafreak.net/Search/$query" |\
  grep -oP "a href=\"\/Manga\/.+?\"" | sort -u)" 

# quit if no search results are found
if [ -z "$response" ]; then
  echo "No results found."
  exit
fi 

title=$(echo "$response" | sed 's/\"//g;s/a\ href=\/Manga\///g' | fzf)

chapters=$(curl -s "https://w12.mangafreak.net/Manga/$title" |\
    grep -oP "Read1.+?\"" | sed 's/\"//g;s/Read1_.\+_//g' | sort -u -n)
lastchapter=$(echo $chapters | rev | cut -d ' ' -f1 | rev)

if [[ $* == *-f* || $* == *-t* ]]; then

  if [ "$FROM" -gt 1 ]; then
    firstchapter=$FROM
  else
    firstchapter=1
  fi

  if [ "$TO" -lt "$lastchapter" ]; then
    lastchapter=$TO
  fi

else
  firstchapter=$(echo "$chapters" | fzf)
  lastchapter=$firstchapter
fi

titlelower=$(echo $title | tr '[:upper:]' '[:lower:]')

mkdir $title
echo "Fetching chapters..."
for chapter in `seq ${firstchapter} ${lastchapter}`; do
  npages=$(curl -s "https://w12.mangafreak.net/Read1_${title}_${chapter}" |\
    grep -oP "of [0-9]+" | sed 's/of\ //g')
  
  mkdir ${title}/ch${chapter}
  for page in `seq 1 ${npages}`; do
    wget -O "${title}/ch${chapter}/p$(echo $page | awk '{printf("%03d", $page)}').jpg" \
      "https://images.mangafreak.net/mangas/${titlelower}/${titlelower}_${chapter}/${titlelower}_${chapter}_${page}.jpg"
    echo "Page "$page
  done
done
